---
collections:
  # https://galaxy.ansible.com/ansible/netcommon
  #- name: ansible.netcommon
  #  version: 1.5.1-dev17
  # https://galaxy.ansible.com/community/vmware
  - name: community.vmware
    version: 2.7.0
  # https://galaxy.ansible.com/community/windows
  #- name: community.windows
  #  version: 1.10.0
  # https://galaxy.ansible.com/infoblox/nios_modules
  - name: infoblox.nios_modules
    version: 1.3.0
  # VMware REST modules
  - name: vmware.vmware_rest