---
#- include_vars: /vars/kerberos_vars.yml

- name: Lookup birth_date Outside of Template (lack of set_temporary_context)
  set_fact:
    birth_date: "{{ lookup('pipe', 'date +%m/%d/%Y\\ %I:%M\\ %p') }}"

# - name: Calculate major and minor versions of OS
#   ansible.builtin.script:
#     cmd: /usr/bin/cat /etc/os-release |grep 'PRETTY_NAME' |awk -F"=" '{print $2}'
#   register: os_version_calc

- name: Fill in the Jinja2 birthcert template
  ansible.builtin.template:
    src: birthcert.xml.j2
    dest: /etc/_birthcert
